plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
}

android {
    namespace 'com.zhangyt.mine'
    compileSdk rootProject.ext.android.compileSdkVersion
    buildToolsVersion rootProject.ext.android.buildToolsVersion
    defaultConfig {
        minSdkVersion rootProject.ext.android.minSdkVersion
        targetSdkVersion rootProject.ext.android.targetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    buildFeatures { viewBinding true }
    resourcePrefix "mine_"
}

kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.name)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-AAROUTER_MODULE_NAME=${project.name}")
}

dependencies {
    api project(path: ':lib_common')
    kapt rootProject.ext.dependencies["arouter-compiler"]
    // WorkManager
    api rootProject.ext.dependencies["worker"]
}
